apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: vote
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - name: "redis-service"
    port: {{ .Values.redis.service.servicePort }}
    targetPort: 6379
  selector:
    app: redis
  
