apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  type: {{ .Values.result.service.type }}
  ports:
  - name: "result-service"
    port: {{ .Values.result.service.servicePort }}
    targetPort: 80
  selector:
    app: result