apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  type: {{ .Values.vote.service.type }}
  ports:
  - name: "vote-service"
    port: {{ .Values.vote.service.servicePort }}
    targetPort: 80
  selector:
    app: vote