apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-helm-release
  namespace: my-namespace
spec:
  interval: 1m
  chart:
    git: my-git-repo
    path: clusters/my-cluster/helmChart-sample-voting-app
    ref: main
  values:
    # Customize your chart values here